#include "steam_discovery.hpp"
#include "loader_session.hpp"
#include <fstream>
#include <algorithm>
#include <cctype>
#include <stdexcept>
namespace channel_expand::loader {
namespace {
constexpr const char* EngineHash="7C21E827722FA7AC9BA4539DC652D3B79F58E240DA49D28E75A1A9A1A88C4173";
struct Node {std::string key,value;std::vector<Node> children;bool object{};};
std::wstring Utf8(const std::string& s){if(s.empty())return {};const int n=MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,s.data(),static_cast<int>(s.size()),nullptr,0);if(!n)throw std::runtime_error("invalid UTF8 in Steam data");std::wstring w(static_cast<size_t>(n),L'\0');MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,s.data(),static_cast<int>(s.size()),w.data(),n);return w;}
class Parser {
 const std::string& s;size_t at{},nodes{};
 void Space(){for(;;){while(at<s.size()&&std::isspace(static_cast<unsigned char>(s[at])))++at;if(at+1<s.size()&&s[at]=='/'&&s[at+1]=='/'){while(at<s.size()&&s[at]!='\n')++at;}else break;}}
 std::string Token(){Space();if(at>=s.size())throw std::runtime_error("truncated Steam data");std::string out;if(s[at]=='"'){++at;bool done=false;while(at<s.size()){char c=s[at++];if(c=='"'){done=true;break;}if(c=='\\'&&at<s.size()&&(s[at]=='\\'||s[at]=='"'))c=s[at++];if(c=='\0')throw std::runtime_error("NUL in Steam data");out+=c;}if(!done)throw std::runtime_error("unterminated Steam string");}else{while(at<s.size()&&!std::isspace(static_cast<unsigned char>(s[at]))&&s[at]!='{'&&s[at]!='}')out+=s[at++];if(out.empty())throw std::runtime_error("invalid Steam token");}return out;}
 std::vector<Node> List(unsigned depth,bool nested){if(depth>32)throw std::runtime_error("Steam nesting limit exceeded");std::vector<Node> out;for(;;){Space();if(at==s.size()){if(nested)throw std::runtime_error("missing Steam closing brace");return out;}if(s[at]=='}'){if(!nested)throw std::runtime_error("unexpected closing brace");++at;return out;}if(++nodes>65536)throw std::runtime_error("Steam node limit exceeded");Node n;n.key=Token();Space();if(at<s.size()&&s[at]=='{'){++at;n.object=true;n.children=List(depth+1,true);}else n.value=Token();out.push_back(std::move(n));}}
 public:explicit Parser(const std::string& text):s(text){if(s.size()>4*1024*1024)throw std::runtime_error("Steam file exceeds4MiB");if(s.find(char(0))!=std::string::npos)throw std::runtime_error("NUL in Steam data");Utf8(s);if(s.size()>=3&&static_cast<unsigned char>(s[0])==0xef&&static_cast<unsigned char>(s[1])==0xbb&&static_cast<unsigned char>(s[2])==0xbf)at=3;}
 std::vector<Node> Parse(){return List(0,false);}
};
const Node* Find(const std::vector<Node>& list,const char* key){const Node* found=nullptr;for(const auto& n:list)if(_stricmp(n.key.c_str(),key)==0){if(found)throw std::runtime_error("duplicate Steam key");found=&n;}return found;}
std::string Read(const std::filesystem::path& path){const auto size=std::filesystem::file_size(path);if(size>4*1024*1024)throw std::runtime_error("Steam file exceeds4MiB");std::ifstream f(path,std::ios::binary);if(!f)throw std::runtime_error("Steam data read failed");std::string out(static_cast<size_t>(size),'\0');if(size&&!f.read(out.data(),static_cast<std::streamsize>(size)))throw std::runtime_error("Steam file changed/truncated");return out;}
void Unique(std::vector<std::wstring>& paths,const std::wstring& path){if(path.empty()||!std::filesystem::path(path).is_absolute())return;const auto normalized=std::filesystem::path(path).lexically_normal().wstring();for(const auto& p:paths)if(_wcsicmp(p.c_str(),normalized.c_str())==0)return;paths.push_back(normalized);}
bool Amd64(const std::filesystem::path& path){std::ifstream f(path,std::ios::binary);IMAGE_DOS_HEADER dos{};if(!f.read(reinterpret_cast<char*>(&dos),sizeof(dos))||dos.e_magic!=IMAGE_DOS_SIGNATURE||dos.e_lfanew<sizeof(dos)||dos.e_lfanew>1024*1024)return false;f.seekg(dos.e_lfanew);DWORD signature{};IMAGE_FILE_HEADER h{};return f.read(reinterpret_cast<char*>(&signature),sizeof(signature))&&f.read(reinterpret_cast<char*>(&h),sizeof(h))&&signature==IMAGE_NT_SIGNATURE&&h.Machine==IMAGE_FILE_MACHINE_AMD64;}
std::wstring Registry(HKEY hive,const wchar_t* subkey,const wchar_t* value,REGSAM view){HKEY key{};if(RegOpenKeyExW(hive,subkey,0,KEY_QUERY_VALUE|view,&key)!=ERROR_SUCCESS)return {};struct Close{HKEY h;~Close(){RegCloseKey(h);}}close{key};DWORD type{},size{};if(RegQueryValueExW(key,value,nullptr,&type,nullptr,&size)!=ERROR_SUCCESS||type!=REG_SZ||size<sizeof(wchar_t)||size>65536||size%sizeof(wchar_t))return {};std::vector<wchar_t> data(size/sizeof(wchar_t)+1,0);if(RegQueryValueExW(key,value,nullptr,&type,reinterpret_cast<BYTE*>(data.data()),&size)!=ERROR_SUCCESS||type!=REG_SZ)return {};return std::wstring(data.data());}
bool Inside(const std::filesystem::path& base,const std::filesystem::path& child){auto a=base.begin(),b=child.begin();for(;a!=base.end();++a,++b)if(b==child.end()||_wcsicmp(a->c_str(),b->c_str()))return false;return b!=child.end();}
}
std::vector<std::wstring> ParseSteamLibraries(const std::string& utf8,const std::wstring& steam_root){const auto tree=Parser(utf8).Parse();const auto root=Find(tree,"libraryfolders");if(!root||!root->object)throw std::runtime_error("missing libraryfolders object");std::vector<std::wstring> paths;Unique(paths,steam_root);for(const auto& node:root->children){if(node.key.empty()||!std::all_of(node.key.begin(),node.key.end(),[](char c){return c>='0'&&c<='9';}))continue;if(!node.object)Unique(paths,Utf8(node.value));else if(const auto value=Find(node.children,"path"))if(!value->object)Unique(paths,Utf8(value->value));}return paths;}
std::wstring ParseInstallDirectory(const std::string& utf8){const auto tree=Parser(utf8).Parse();const auto root=Find(tree,"AppState");if(!root||!root->object)throw std::runtime_error("missing AppState");const auto id=Find(root->children,"appid"),dir=Find(root->children,"installdir");if(!id||id->value!="4000"||!dir||dir->object)throw std::runtime_error("manifest is not GMod4000");const auto text=Utf8(dir->value);const std::filesystem::path path(text);if(text.empty()||path.is_absolute()||path.has_root_name()||text.find(L':')!=std::wstring::npos)throw std::runtime_error("invalid installdir");for(const auto& part:path)if(part==L".."||part==L"."||part.empty())throw std::runtime_error("installdir escape rejected");return path.wstring();}
InstallCandidate ValidateInstallRoot(const std::wstring& root){InstallCandidate c;c.root=root;try{const auto r=std::filesystem::canonical(root);c.root=r.wstring();const auto bin=r/L"bin"/L"win64";c.game=(bin/L"gmod.exe").wstring();c.engine=(bin/L"engine.dll").wstring();c.client=(bin/L"client.dll").wstring();if(!Amd64(c.game)||!Amd64(c.engine)||!Amd64(c.client)){c.reason=L"missing AMD64 game/engine/client";return c;}std::wstring why;std::string hash;if(!FileSha256(c.engine,hash,why)){c.reason=why;return c;}c.supported=hash==EngineHash;c.reason=c.supported?L"supported engine build":L"unsupported engine SHA256";}catch(const std::exception& e){c.reason=Wide(e.what());}return c;}
DiscoveryResult DiscoverSteamInstalls(){DiscoveryResult out;std::vector<std::wstring> steam,libs;for(const auto view:{KEY_WOW64_64KEY,KEY_WOW64_32KEY}){Unique(steam,Registry(HKEY_CURRENT_USER,L"Software\\Valve\\Steam",L"SteamPath",view));Unique(steam,Registry(HKEY_LOCAL_MACHINE,L"Software\\Valve\\Steam",L"InstallPath",view));}
 for(const auto& root:steam){Unique(libs,root);try{for(const auto& lib:ParseSteamLibraries(Read(std::filesystem::path(root)/L"steamapps"/L"libraryfolders.vdf"),root))Unique(libs,lib);}catch(const std::exception& e){out.diagnostics.push_back(root+L": "+Wide(e.what()));}}
 for(const auto& lib:libs){try{const auto apps=std::filesystem::path(lib)/L"steamapps",manifest=apps/L"appmanifest_4000.acf";if(!std::filesystem::exists(manifest))continue;const auto dir=ParseInstallDirectory(Read(manifest));const auto common=std::filesystem::weakly_canonical(apps/L"common"),root=std::filesystem::weakly_canonical(common/dir);if(!Inside(common,root))throw std::runtime_error("resolved install escapes library common");auto c=ValidateInstallRoot(root.wstring());c.source=manifest.wstring();bool duplicate=false;for(const auto& old:out.candidates)if(SamePath(old.root,c.root))duplicate=true;if(!duplicate)out.candidates.push_back(std::move(c));}catch(const std::exception& e){out.diagnostics.push_back(lib+L": "+Wide(e.what()));}}
 return out;
}
bool SelfCheckDiscovery(std::wstring& why){try{
 const auto require=[](bool pass){if(!pass)throw std::runtime_error("discovery assertion failed");};
 require(ParseSteamLibraries("\"libraryfolders\" { \"1\" { \"path\" \"L:/SteamLibrary\" } \"2\" \"L:/SteamLibrary\" }",L"D:/Steam").size()==2);
 require(ParseSteamLibraries("//comment\n\"libraryfolders\" {}",L"D:/Steam").size()==1);
 require(ParseSteamLibraries("\"libraryfolders\" { \"1\" {\"path\" \"L:\\\\Unicode space\"} }",L"D:/Steam").at(1)==L"L:\\Unicode space");
 require(ParseSteamLibraries("\"libraryfolders\" {\"1\" {\"path\" \"L:/\xE4\xB8\xAD\xE6\x96\x87\"}}",L"D:/Steam").size()==2);
 require(ParseInstallDirectory("\"AppState\"{\"appid\"\"4000\"\"installdir\"\"GarrysMod\"}")==L"GarrysMod");
 for(const auto& text:{std::string("\"libraryfolders\"{"),std::string("\"libraryfolders\"{} }"),std::string(4*1024*1024+1,'x'),std::string("\xff")}){bool rejected=false;try{ParseSteamLibraries(text,L"D:/Steam");}catch(...){rejected=true;}require(rejected);}
 for(const auto& dir:{"../escape","C:/absolute","GarrysMod:stream","folder/../escape",""}){bool rejected=false;try{ParseInstallDirectory(std::string("\"AppState\"{\"appid\"\"4000\"\"installdir\"\"")+dir+"\"}");}catch(...){rejected=true;}require(rejected);}
 std::string nested="\"libraryfolders\"{";for(int i=0;i<34;++i)nested+="\"x\"{";nested+=std::string(35,'}');bool depth_rejected=false;try{ParseSteamLibraries(nested,L"D:/Steam");}catch(...){depth_rejected=true;}require(depth_rejected);
 std::string many="\"libraryfolders\"{";for(int i=0;i<65536;++i)many+="\"x\"\"y\"";many+="}";bool nodes_rejected=false;try{ParseSteamLibraries(many,L"D:/Steam");}catch(...){nodes_rejected=true;}require(nodes_rejected);
 bool reject=false;try{ParseInstallDirectory("\"AppState\"{\"appid\"\"4020\"\"installdir\"\"GarrysMod\"}");}catch(...){reject=true;}require(reject);require(!Inside(L"L:/lib/common",L"L:/lib/common-other/game"));require(Inside(L"L:/lib/common",L"L:/lib/common/game"));return true;
 }catch(const std::exception& e){why=Wide(e.what());return false;}}
}
